### ISSUE TITLE
camelot-test plugin doesn't work as expected for multi-module projects

### ISSUE THREAD

**Issue by vania-pooh** [camelot-framework/camelot#28]
Consider the following layout:
```
root >
    pom.xml <-- this one contains camelot-test plugin in pluginManagement section
    module >
        pom.xml <-- this one contains camelot-test plugin in build->plugins
```
Getting an exception when running the plugin from the root directory (need to change directory to module):
```bash
$ mvn clean compile camelot-test:run
.... (a lot of output)
org.springframework.beans.factory.BeanInitializationException: Cannot initialize plugins system: config not found! Paths=[]
	at ru.yandex.qatools.camelot.core.impl.GenericPluginsEngine.loadConfigs(GenericPluginsEngine.java:391)[camelot-core-2.1.12.jar:]
	at ru.yandex.qatools.camelot.core.impl.GenericPluginsEngine.getConfigs(GenericPluginsEngine.java:149)[camelot-core-2.1.12.jar:]
	at ru.yandex.qatools.camelot.core.impl.GenericPluginsEngine.getPluginsMap(GenericPluginsEngine.java:231)[camelot-core-2.1.12.jar:]
	at ru.yandex.qatools.camelot.core.impl.ProcessingEngineImpl$1.onCamelContextStarted(ProcessingEngineImpl.java:86)[camelot-core-2.1.12.jar:]
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:1987)[camel-core-2.13.2.jar:2.13.2]
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:1851)[camel-core-2.13.2.jar:2.13.2]
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:1683)[camel-core-2.13.2.jar:2.13.2]
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)[camel-core-2.13.2.jar:2.13.2]
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:1651)[camel-core-2.13.2.jar:2.13.2]
	at org.apache.camel.spring.SpringCamelContext.maybeStart(SpringCamelContext.java:254)[camel-spring-2.13.2.jar:2.13.2]
	at org.apache.camel.spring.SpringCamelContext.onApplicationEvent(SpringCamelContext.java:120)[camel-spring-2.13.2.jar:2.13.2]
	at org.apache.camel.spring.CamelContextFactoryBean.onApplicationEvent(CamelContextFactoryBean.java:318)[camel-spring-2.13.2.jar:2.13.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:96)[spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:334)[spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:948)[spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)[spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)[spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)[spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)[spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:799)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:499)[jetty-servlet-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:790)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:337)[jetty-servlet-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1343)[jetty-webapp-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)[jetty-webapp-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:742)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)[jetty-webapp-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.Server.start(Server.java:399)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)[jetty-server-9.3.0.M1.jar:9.3.0.M1]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)[jetty-util-9.3.0.M1.jar:9.3.0.M1]
	at ru.yandex.qatools.camelot.maven.service.CamelotJettyRunner.run(CamelotJettyRunner.java:85)[camelot-extensions-2.1.12.jar:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483)[:1.8.0_20]
	at ru.yandex.qatools.camelot.maven.service.CamelotRunner.runNotForked(CamelotRunner.java:275)[camelot-extensions-2.1.12.jar:]
	at ru.yandex.qatools.camelot.maven.service.CamelotRunner.run(CamelotRunner.java:102)[camelot-extensions-2.1.12.jar:]
	at ru.yandex.qatools.camelot.maven.RunMojo.execute(RunMojo.java:199)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_20]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_20]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_20]
	at java.lang.reflect.Method.invoke(Method.java:483)[:1.8.0_20]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)[plexus-classworlds-2.5.2.jar:]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)[plexus-classworlds-2.5.2.jar:]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)[plexus-classworlds-2.5.2.jar:]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)[plexus-classworlds-2.5.2.jar:]
```

**Comment by smecsia** [comment]
How do you think the plugin should work in this case? Maven Reactor build process uses all the modules separately. For example. try to use jetty-maven-plugin the same way, you've described, and you will get an exception as well.

**Comment by vania-pooh** [comment]
@smecsia we should either fix the issue so it works for this case or specify this case in documentation \ FAQ.

**Comment by vania-pooh** [comment]
Created such question: http://stackoverflow.com/questions/29333706/camelot-test-maven-plugin-config-not-found-paths
